on:
  push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Build in Debug mode
        run: dotnet build --no-restore

  test:
      runs-on: ubuntu-latest
      steps:
        - name: Build in Debug mode
          run: dotnet build
        - name: test
          run: dotnet test